import os
from dotenv import load_dotenv

load_dotenv()

AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_KEY = os.getenv("AZURE_OPENAI_API_KEY") or os.getenv("AZURE_OPENAI_KEY")
AZURE_OPENAI_DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT")
AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT = os.getenv("AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT")
AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION") or "2024-10-01-preview"
AZURE_SEARCH_SERVICE_ENDPOINT = os.getenv("AZURE_SEARCH_SERVICE_ENDPOINT")
AZURE_SEARCH_SERVICE_ADMIN_KEY = os.getenv("AZURE_SEARCH_ADMIN_KEY")
AZURE_SEARCH_SERVICE_INDEX_NAME = os.getenv("AZURE_SEARCH_SERVICE_INDEX_NAME") or "azure-storage-research2"
AZURE_STORAGE_CONNECTION_STRING = os.getenv("AZURE_STORAGE_CONNECTION_STRING")
AZURE_AI_MULTISERVICE_KEY = os.getenv("AZURE_AI_MULTISERVICE_KEY")

# Azure Search and OpenAI resource/config names
VECTOR_SEARCH_PROFILE_NAME = "ragresearchHnswProfile"
VECTOR_ALGORITHM_NAME = "ragresearchHnsw"
VECTORIZER_NAME = "ragresearch_vectoriser"
SEMANTIC_CONFIG_NAME = "ragresearch-semantic-config"
SCORING_PROFILE_NAME = "ragresearch-scoring-profile"
SKILLSET_NAME = "ragresearch-ss"
DATASOURCE_NAME = "ragdatastore"
INDEXER_NAME = AZURE_SEARCH_SERVICE_INDEX_NAME
BLOB_CONTAINER_NAME = "fileupload-researchpaper"
